### ISSUE TITLE
Reference panel

### ISSUE THREAD

**Issue by mhsteppan** [huwenboshi/hess#11]
I encounter an error with the reference panel. 
I used the link you provided https://ucla.box.com/shared/static/l8cjbl5jsnghhicn0gdej026x017aj9u.gz from 1000genomes.
I get the following error message:

[ERROR] Missing files for the reference panel l8cjbl5jsnghhicn0gdej026x017aj9u.gz

what could be the problem here?
kind regards,
martin

**Comment by huwenboshi** [comment]
did you decompress the files?
