### ISSUE TITLE
refpanel in step 1

### ISSUE THREAD

**Issue by Mary-mufford** [huwenboshi/hess#12]
Hi there,

While running step 1. I come across an error saying module not found "refpanel" when executing estimation.py. I can't seem to find any modules called refpanel.

Please could you help m resolve this?

![image](https://user-images.githubusercontent.com/66270009/97162368-c9e23100-1787-11eb-9f66-bed7fa41772e.png)

**Comment by zhuxxyy12** [comment]
Could you please tell me how to solve it? I met the same problem.
