### ISSUE TITLE
Step 2 local rg routine:  AttributeError: 'float' object has no attribute 'sqrt'

### ISSUE THREAD

**Issue by dantylee** [huwenboshi/hess#2]
(myenv27) C:\Users\danty\Dropbox\hess\h>python hess.py --prefix step1h_trait1 --out step2h_trait1
[INFO] Command started at: Fri, 09 Feb 2018 16:47:45
[INFO] Command issued:
    hess.py \
        --prefix step1h_trait1 \
        --out step2h_trait1
[INFO] Loaded results for 1568 loci from step 1
[INFO] Using 4133481 SNPs with average sample size 77096.0
[INFO] Re-inflate the summary statistics with lambda_gc: 1
[INFO] Total SNP-heritability estimate: 0.606 (0.00698)
Traceback (most recent call last):
  File "hess.py", line 217, in <module>
    main()
  File "hess.py", line 40, in main
    argmap['gwse-thres'], argmap['tot-hsqg'], argmap['out'])
  File "C:\Users\danty\Dropbox\hess\h\src\estimation.py", line 174, in local_hsqg_step2
    min_eigval, reinflate, gwse_thres)
  File "C:\Users\danty\Dropbox\hess\h\src\estimation.py", line 285, in local_hsqg_step2_helper
    se = np.sqrt(local_hsqg_est_var)
AttributeError: 'float' object has no attribute 'sqrt'

**Comment by huwenboshi** [comment]
This seems to be an issue with NumPy. Which version of NumPy are you using?

**Comment by dantylee** [comment]
Ah!  Yes, thank you!   I was using latest versions of packages, but I downgraded to nearest available and this solved the problem.

    matplotlib: 2.1.2-py27ha51faf0_0  --> 1.4.3-np110py27_3
    mkl:        2018.0.1-h2108138_4   --> 11.3.1-0
    numpy:      1.14.0-py27hfef472a_1 --> 1.10.4-py27_0
    pandas:     0.22.0-py27hc56fc5f_0 --> 0.18.1-np110py27_0
    pyqt:       5.6.0-py27h224ed30_5  --> 4.10.4-py27_1
    scipy:      1.0.0-py27h7cd1477_0  --> 0.16.1-np110py27_1

**Comment by ape4fld** [comment]
If anyone encounters the same issue even with the same numpy version as above, I was able to fix it by defining `local_hsqg_est_var = local_hsqg_est_var.astype('float64')` in estimation.py (line 282).
