### ISSUE TITLE
Step 1 error

### ISSUE THREAD

**Issue by sonia-shah** [huwenboshi/hess#3]
[INFO] @----------------------------------------------------------@
       |         HESS       |      v0.5      |    9/October/2017  |
       |----------------------------------------------------------|
       |  (C) 2017 Huwenbo Shi, GNU General Public License, v3    |
       |----------------------------------------------------------|
       |  For documentation, citation & bug-report instructions:  |
       |   http://bogdan.bioinformatics.ucla.edu/software/hess/   |
       @----------------------------------------------------------@
[INFO] Command started at: Tue, 29 May 2018 12:25:40
[INFO] Command issued:
    /Users/sonia.shah/Documents/Software/hess-0.5.4-beta/hess.py \
        --bfile ukbEUR_imp_chr1_v2_imp_QC_HRC_random10Ksubset \
        --local-rhog trait1 trait2
        --partition fourier_ls-chr1.bed \
        --out step1 \
        --chrom 1
[INFO] Loaded 133 partitions on chromosome 1
[INFO] Average window size is 1873901
[INFO] 2256485 SNPs read from reference panel
[INFO] Loaded 636448 SNPs with rs IDs and single-letter alleles on chromosome 1 from the GWAS summary data file
Traceback (most recent call last):
  File "/Users/sonia.shah/Documents/Software/hess-0.5.4-beta/hess.py", line 217, in <module>
    main()
  File "/Users/sonia.shah/Documents/Software/hess-0.5.4-beta/hess.py", line 45, in main
    argmap['out'])
  File "/Users/sonia.shah/Documents/Software/hess-0.5.4-beta/src/estimation.py", line 390, in local_rhog_step1
    sumstats1.filter_sumstats(refpanel.get_map())
  File "/Users/sonia.shah/Documents/Software/hess-0.5.4-beta/src/sumstats.py", line 168, in filter_sumstats
    elif a1a0 in reverse[a1a2]: flip.append(i)
KeyError: 'tc'

**Comment by huwenboshi** [comment]
Thanks for letting me know. The issues seems to be caused by the fact that the alleles in the summary stats files are in lower case. Could you try changing the alleles from lower case to upper cases?

**Comment by sonia-shah** [comment]
One of the files has lower case alleles. After changing to upper caseI got another error because indel alleles were coded as I or D. So I removed these and it's running now. Thanks for the troubleshooting
