### ISSUE TITLE
SNPs

### ISSUE THREAD

**Issue by frucelee** [huwenboshi/hess#34]
Hi,

Thanks a lot for the very nice software. I have a stupid question. We want to calculate some genetic correlation using GWASs data from finngen  and UK biobank. As we known that very high density SNPs were included in finngen study as a results a very long time needed for the analysis. Is it possible for us to keep only same SNPs for finngen in UK biobank during the analysis?, and it would affect the results? Thanks a lot.

Lee

**Comment by DaXuanGarden** [comment]
I have the same issue. How can you solve the problem of using FinnGen and UKBdata which causes too long running time? What are your typical uptime? Thank you so much!
Best regards
Daxuan
