### ISSUE TITLE
Step 2 error

### ISSUE THREAD

**Issue by kglanville** [huwenboshi/hess#5]
Hello, 

I receive the following error when running step2 and specifying the h2 and se. Any assistance would be appreciated. 

[INFO] Command started at: Wed, 13 Mar 2019 11:43:37
[INFO] Command issued:
    hess.py \
        --tot-hsqg 0.087 0.004 \
        --prefix step1 \
        --out step2_total_h2

~/HESS/hess-0.5.3-beta/src/estimation.py:126: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  compression='gzip', names=['start', 'stop', 'nsnp', 'rank', 'N'])
[INFO] Loaded results for 1703 loci from step 1
Traceback (most recent call last):
  File "hess.py", line 217, in <module>
    main()
  File "hess.py", line 40, in main
    argmap['gwse-thres'], argmap['tot-hsqg'], argmap['out'])
  File "~/HESS/hess-0.5.3-beta/src/estimation.py", line 180, in local_hsqg_step2
    max_num_eig, min_eigval, reinflate, gwse_thres, tot_hsq)
  File "~/HESS/hess-0.5.3-beta/src/estimation.py", line 307, in local_hsqg_step2_helper_tot_hsq
    if len(reinflate) > 1:
TypeError: object of type 'float' has no len()

**Comment by huwenboshi** [comment]
This bug should have been fixed in a newer version (v0.5.4-beta).
https://github.com/huwenboshi/hess/archive/v0.5.4-beta.zip
